name       : liblouis
version    : 3.7.0
release    : 5
source     :
    - https://github.com/liblouis/liblouis/releases/download/v3.7.0/liblouis-3.7.0.tar.gz : 842a86091d78979cd8d1705936de1735b8ff6b9c961781d292fa9783f3f6335c
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Braille translation and back-translation library
description: |
    Liblouis is an open-source braille translator and back-translator named in honor of Louis Braille. It features support for computer and literary braille, supports contracted and uncontracted translation for many languages and has support for hyphenation. New languages can easily be added through tables that support a rule- or dictionary based approach. Tools for testing and debugging tables are also included. Liblouis also supports math braille (Nemeth and Marburg).
builddeps  :
    - texinfo
    - help2man
setup      : |
    %configure --disable-static
build      : |
    %make -j1
install    : |
    %make_install

    cd python
    LD_PRELOAD+=":$workdir/liblouis/.libs/liblouis.so"
    %python_install
check      : |
    %make check
