name       : liblouis
version    : 3.3.0
release    : 2
source     :
    - https://github.com/liblouis/liblouis/releases/download/v3.3.0/liblouis-3.3.0.tar.gz : 3466c9d55ad23191ec1b092b911c706475156556176ead9ecd7ee841df6a31f3
license    :
    - GPL-3.0
component  : desktop.library
summary    : Braille translation and back-translation library
description: |
    Liblouis is an open-source braille translator and back-translator named in honor of Louis Braille. It features support for computer and literary braille, supports contracted and uncontracted translation for many languages and has support for hyphenation. New languages can easily be added through tables that support a rule- or dictionary based approach. Tools for testing and debugging tables are also included. Liblouis also supports math braille (Nemeth and Marburg).
builddeps  :
    - texinfo
    - help2man
setup      : |
    %configure --disable-static
build      : |
    %make -j1
    cd python
    LD_LIBRARY_PATH=$workdir/liblouis/.libs %python_setup
install    : |
    %make_install
    cd python
    LD_LIBRARY_PATH=$workdir/liblouis/.libs %python_install
check      : |
    %make check
